### ISSUE TITLE
Can't run server part

### ISSUE THREAD

**Issue by mzylowski** [GroupProjectWETI/OpenVillage#10]
After install from our prepare_env ansibles my version of node
```
czarodziej@lenovoB51:~/Repos/OpenVillage/back-end$ node -v
v0.10.25

```
and npm: 
```
czarodziej@lenovoB51:~/Repos/OpenVillage/back-end$ npm -v
1.3.10

```
And the error in server build
```
[4mRunning "jshint:server" (jshint) task[24m

✔ No problems


[4mRunning "jshint:serverTest" (jshint) task[24m

✔ No problems


[4mRunning "test" task[24m

[4mRunning "env:all" (env) task[24m

[4mRunning "env:test" (env) task[24m

[4mRunning "mocha_istanbul:src" (mocha_istanbul) task[24m
=============================================================================
Writing coverage object [/home/czarodziej/Repos/OpenVillage/back-end/coverage/partial/nodejs/coverage.json]
Writing coverage reports at [/home/czarodziej/Repos/OpenVillage/back-end/coverage/partial/nodejs]
=============================================================================
------------------------|-----------|-----------|-----------|-----------|
File                    |   % Stmts |% Branches |   % Funcs |   % Lines |
------------------------|-----------|-----------|-----------|-----------|
   api/                 |      0.98 |         0 |         0 |      0.98 |
      users.js          |      0.98 |         0 |         0 |      0.98 |
   components/          |        80 |       100 |         0 |        80 |
      constants.js      |        50 |       100 |         0 |        50 |
      http-statuses.js  |       100 |       100 |       100 |       100 |
   config/              |       100 |       100 |       100 |       100 |
      config.js         |       100 |       100 |       100 |       100 |
   entities/            |     21.05 |         0 |         0 |     21.05 |
      token-entities.js |        25 |         0 |         0 |        25 |
      users-entities.js |     19.64 |         0 |         0 |     19.64 |
   lib/logger/          |       100 |       100 |       100 |       100 |
      logger.js         |       100 |       100 |       100 |       100 |
   lib/utils/           |     14.29 |       100 |         0 |     14.29 |
      security-tools.js |     14.29 |       100 |         0 |     14.29 |
------------------------|-----------|-----------|-----------|-----------|
All files               |     18.36 |         0 |      1.37 |     18.36 |
------------------------|-----------|-----------|-----------|-----------|


/home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/node_modules/bindings/bindings.js:91
  throw err
        ^
Error: Could not locate the bindings file. Tried:
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/build/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/Release/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/compiled/0.10.25/linux/x64/bcrypt_lib.node
    at bindings (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/server/lib/utils/security-tools.js:9:50)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/hook.js:99:20)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/czarodziej/Repos/OpenVillage/back-end/server/api/users.js:9:303
    at Object.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/server/api/users.js:108:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/hook.js:99:20)
    at Module.load (module.js:356:32)
    at Object.load (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/rewire/lib/moduleEnv.js:20:18)
    at internalRewire (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/rewire/lib/rewire.js:57:15)
    at rewire (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/rewire/lib/index.js:11:12)
    at Object.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/server/test/api/users.spec.js:6:16)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /home/czarodziej/Repos/OpenVillage/back-end/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/mocha/lib/mocha.js:485:10)
    at Object.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/mocha/bin/_mocha:403:18)
    at Module._compile (module.js:456:26)
    at Module._extensions..js (module.js:474:10)
    at Object.Module._extensions..js (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/hook.js:101:13)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at runFn (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/command/common/run-with-cover.js:116:16)
    at /home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/command/common/run-with-cover.js:240:17
    at /home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/util/file-matcher.js:56:16
    at /home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/lib/util/file-matcher.js:35:9
    at Object.next (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/lib/fileset.js:41:14)
    at Fileset.EventEmitter.emit (events.js:95:17)
    at Fileset.next (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:343:12)
    at Fileset.Glob._processEmitQueue (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:310:12)
    at Fileset.Glob.emitMatch (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:290:8)
    at Fileset.Glob._finish (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:230:8)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:183:27)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:483:32)
    at Fileset.cb (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:368:11)
    at Fileset.<anonymous> (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:450:14)
    at Fileset.Glob._afterReaddir (/home/czarodziej/Repos/OpenVillage/back-end/node_modules/istanbul/node_modules/fileset/node_modules/glob/glob.js:695:17)
    at Object.oncomplete (fs.js:107:15)
[31m>> [39m
[33mWarning: Task "mocha_istanbul:src" failed. Use --force to continue.[39m

[31mAborted due to warnings.[39m


Execution Time (2016-08-29 21:22:39 UTC)
loading tasks       577ms  ▇▇▇▇▇▇▇ 15%
jshint:server       277ms  ▇▇▇▇ 7%
jshint:serverTest    91ms  ▇▇ 2%
mocha_istanbul:src   2.9s  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 75%
Total 3.8s

```

**Comment by ajoskows** [comment]
At beginning you should remove old version of nodejs on your computer (http://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x). Next you can install it via ansible
